### ISSUE TITLE
Please add a license for right to use.

### ISSUE THREAD

**Issue by poonnawit** [petotamas/pyArgus#6]
This project is interesting and very useful.
I have seen in these code are mark at the top with license GPLv3
So, I suggest owner of this project, please add a LICENSE.md to inform how users can do with this code.

Thank you in advance.

For any further licensing information, please see [https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by petotamas** [comment]
Thank you for your attention call. I have added the license file.
